// Generated by CoffeeScript 1.9.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.transformwords = {};

}).call(this);

//# sourceMappingURL=transform-words.js.map
